use dummydb;
#144 id ar employeer ar cheye kom jadr salary
SELECT *
FROM EMPLOYEES
WHERE SALARY < (SELECT SALARY
				FROM EMPLOYEES
                WHERE EMPLOYEE_ID=144
                );
                
#MAX SALARY AR EMPLOYEE DETAILS
SELECT *
FROM EMPLOYEES
WHERE SALARY = ( SELECT MAX(SALARY)
				FROM EMPLOYEES
                );
                
#THOSE EMPLOYEES WHO ARE IN MARKETING DEPT
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID=(
					SELECT DEPARTMENT_ID
                    FROM DEPARTMENTS
                    WHERE DEPARTMENT_NAME = 'MARKETING'
                    );
#HOW MANY EMPLOYEES FROM IT DEPT
SELECT COUNT(*) AS MEMBERS
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
					SELECT DEPARTMENT_ID
                    FROM DEPARTMENTS
                    WHERE DEPARTMENT_NAME = 'IT'
                    );

SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE JOB_ID = (SELECT JOB_ID
				FROM JOBS
                WHERE JOB_TITLE='PROGRAMMER'
                );
 ------ ADVANCED SUBQUERY ------
 #2ND HIGHEST WITH SUBQUERY
 SELECT *
 FROM EMPLOYEES
 WHERE SALARY = (
				SELECT MAX(SALARY)
                FROM EMPLOYEES
                WHERE SALARY < (SELECT MAX(SALARY)
								FROM EMPLOYEES
                                )
				);

#ADVANCED TECHNIQUE TO IDENTIFY THE PEOPLE WHO HAVE HIGHER SALARY THEN MANAGER
SELECT *
FROM EMPLOYEES AS EMP
WHERE SALARY > (SELECT SALARY
				FROM EMPLOYEES AS MGR
                WHERE EMP.MANAGER_ID=MGR.EMPLOYEE_ID
                );
#PEOPLE WHO HAVE THE SAME JOB_ID AS THEIR MANAGER
SELECT *
FROM EMPLOYEES AS EMP
WHERE JOB_ID = (SELECT JOB_ID
				FROM EMPLOYEES AS MGR
                WHERE EMP.MANAGER_ID=MGR.EMPLOYEE_ID
                );
                
	-- COMMON TABLE EXPRESSION--
#THOSE WHO HAVE SALARIES GREATER THEN AVG IT SALARY AND LESS THEN MAX MARKETING SALARY

WITH AVGIT AS(
				SELECT AVG(SALARY) AS SAL1
                FROM EMPLOYEES
                WHERE DEPARTMENT_ID=60 -- IT
			),
MAXMKT AS(
		SELECT MAX(SALARY) AS SAL2
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID=20 -- MARKETING
        )
SELECT *
FROM EMPLOYEES
WHERE SALARY > (SELECT SAL1 FROM AVGIT) AND SALARY < (SELECT SAL2 FROM MAXMKT);


USE DUMMYDB;
#3RD HIGHEST SALARY
SELECT *
 FROM EMPLOYEES
 WHERE SALARY = (
				SELECT MAX(SALARY)
                FROM EMPLOYEES
                WHERE SALARY < (SELECT MAX(SALARY)
								FROM EMPLOYEES
                                WHERE SALARY < (SELECT MAX(SALARY)
												FROM EMPLOYEES
												)
                                )
				);
                
#3RD LOWEST SALARY
SELECT *
 FROM EMPLOYEES
 WHERE SALARY = (
				SELECT MIN(SALARY)
                FROM EMPLOYEES
                WHERE SALARY > (SELECT  MIN(SALARY)
								FROM EMPLOYEES
                                WHERE SALARY > (SELECT  MIN(SALARY)
												FROM EMPLOYEES
												)
                                )
				);
                
#ABOVE 2 QUERIES USING COMMON EXPRESSION TABLE

#HIRED AFTER STEVEN
SELECT *
FROM EMPLOYEES
WHERE HIRE_DATE > ANY (SELECT HIRE_DATE
					FROM EMPLOYEES
                    WHERE first_name='Steven' 
                    );

